# This is a basic workflow to help you get started with Actions

 name: Discussion Thread

 # Controls when the workflow will run
 on:
   workflow_dispatch:
     inputs:
       version_name:
         description: 'Version name of the release candidate build'
         required: false
       release_thread_id:
         description: 'ID of the release discussion thread on the repo'
         required: false

 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   check_new_fixes:
     name: 'To create new discussion for RC'
     runs-on: ubuntu-latest
     steps:
       # 1. Get the repo id
       - uses: octokit/graphql-action@v2.x
         id: get_repo_id
         with:
           query: |
             query {
               repository(owner: "zhankit", name: "${{ github.event.repository.name }}") {
                 id
               }
             }
           owner: "zhankit"
           repo: ${{ github.event.repository.name }}
           discussion_number: ${{ github.event.inputs.release_thread_id }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

       - run: echo "${{ steps.get_repo_id.outputs }}" "${{ steps.get_repo_id.outputs.data }}" "${{ toJSON(steps.get_repo_id.outputs).repository }}" "${{ toJSON(steps.get_repo_id.outputs.data.repository) }}"
 
       # 2. Create discussion
       - uses: octokit/graphql-action@v2.x
         id: get_release_thread
         with:
           query: |
             mutation {
               # input type: CreateDiscussionInput
               createDiscussion(input: {repositoryId: "${{ steps.get_repo_id.outputs.data.repository.id }}", categoryId: "General", body: "The body", title: "The title"}) {

                 # response type: CreateDiscussionPayload
                 discussion {
                   id
                 }
               }
             }
           repo: ${{ github.event.repository.name }}
           discussion_number: ${{ github.event.inputs.release_thread_id }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - run: "echo api response: ${{ steps.get_release_thread.outputs.data }}"
