 # This is a basic workflow to help you get started with Actions

 name: Discussion Thread

 # Controls when the workflow will run
 on:
   workflow_dispatch:

 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   check_new_fixes:
     name: 'To create new discussion for RC'
     runs-on: macos-latest
     steps:
     
           # 1. Check out Code
       - name: Checkout code
         uses: actions/checkout@v2
         with:
           ref: 'master'
           token: ${{ secrets.GITHUB_TOKEN }}
           fetch-depth: 0
       
     
      # 1. Get discussion list in this repository
       - uses: octokit/graphql-action@v2.x
         id: get_discussion_id
         with:
           query: |
             query discussion($owner: String!, $repo:String!) {
               repository(owner: $owner, name: $repo) {
                 discussionCategories(first: 10) {
                   nodes {
                     # type: Discussion
                     id
                     name
                   }
                 }
               }
             }
           owner: "zhankit"
           repo: ${{ github.event.repository.name }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

       # 2. Get Repository ID
       - uses: octokit/graphql-action@v2.x
         id: get_repo_id
         with:
           query: |
             query repo($owner: String!, $repo:String!) {
               repository(owner: $owner, name: $repo) {
                 id
               }
             }
           owner: "zhankit"
           repo: ${{ github.event.repository.name }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
       - name: export
         id: version
         shell: bash
         run: |
          git fetch;
          RC_VERSION=7.43.0
          echo "::set-output name=TAG_NAME::$(git log origin/release/$RC_VERSION..origin/master --oneline --merges --grep="pull request")"
        

       - name: Processing Git differences
         id: get_git_differences
         shell: bash
         run: |
          #!/usr/bin/env bash
          
          git fetch;
          RC_VERSION=7.43.0

          BODY=$(git log origin/release/$RC_VERSION..origin/master --oneline --merges --grep="pull request");
          echo 'DISCUSSION_BODY<<EOF' >> $GITHUB_ENV
          echo "$BODY" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV


       # 4. Create discussion
       - uses: octokit/graphql-action@v2.x
         id: get_release_thread
         with:
           query: |
             mutation newDiscussion($repositoryid: String!, $categoryid: String!, $body: String!, $title: String! ){
               # input type: CreateDiscussionInput
               createDiscussion(input: {repositoryId: $repositoryid, categoryId: $categoryid, body: $body, title: $title}) {

                 # response type: CreateDiscussionPayload
                 discussion {
                   id
                   number
                 }
               }
             }
           repositoryid: "${{ fromJson(steps.get_repo_id.outputs.data).repository.id }}"
           categoryid: "DIC_kwDOFW434s4CATF2"
           body: |
            "${{ env.DISCUSSION_BODY }}"
           title: "${{ fromJson(steps.get_repo_id.outputs.data).repository.id }}"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           
           
       - run: "echo api response: ${{ steps.get_release_thread.outputs.data }}"

           
       - run: "echo api response: ${{ fromJson(steps.get_release_thread.outputs.data).createDiscussion.discussion.number }}"
