# This is a basic workflow to help you get started with Actions

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      version_name:
        # i.e. v3.0.0, v7.39.0-rc1
        description: 'Version of the release candidate build (RC)'
        required: true
      release_thread_id:
        description: 'ID of the release discussion thread on the repo'
        required: true
      conflunece_release_note:
        description: 'Confleunce Release note URL'
        required: true
        

name: RC Release

jobs:
  build:
    name: RC Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Echo site details
        env:
          SITE: ${{ matrix.site }}
          DATACENTER: ${{ matrix.datacenter }}
        run: 
          #!/bin/bash

          # current Git branch
          branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

          # current project name
          projectName=$(git config --local remote.origin.url|sed -n 's#.*/\([^.]*\)\.git#\1#p')

          # establish master branch name variables
          masterBranch=$branch

          # checkout to master branch, this will break if the user has uncommited changes
          git checkout $masterBranch


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          repository: release/${{ github.event.inputs.version_name }}
          tag_name: release-${{ github.event.inputs.version_name }}
          release_name: v${{ github.event.inputs.version_name }}
          body: |
            Release notes:
            ${{ github.event.inputs.conflunece_release_note }}
            
            Release thread:
            https://github.com/MoneyLion/mobile-app/discussions/${{ github.event.inputs.release_thread_id }}
          draft: true
          prerelease: false
